#!/bin/sh
#
#Copia de seguridade do cartafol /etc/apt
if [ ! -f /etc/apt.tar.gz ];
	then
		sudo tar -zcvf /etc/apt.tar.gz /etc/apt;
fi

#Comprobar version do repoubuntumateedu2004
ver_repoubuntumateedu2004=`egrep -c '#ver20200417.1' /usr/bin/repoubuntumateedu2004`;
if [ "$ver_repoubuntumateedu2004" != "1" ];
	then
		sudo cp -f /home/adminpc/.RepoUbuntuMateEdu2004/trunk/repoubuntumateedu2004 /usr/bin/repoubuntumateedu2004;
fi

#Instalación do grub-customizer
pkg_grubcustomizer=$(dpkg-query -W --showformat='${Status}\n' grub-customizer|grep "install ok installed");
if [ 'install ok installed' != "$pkg_grubcustomizer" ];
	then
		sudo apt install -y grub-customizer;
fi

#Corrección da configuración do grub
grub_hidden=`egrep -c 'GRUB_TIMEOUT_STYLE="hidden"' /etc/default/grub`;
if [ "$grub_hidden" != "0" ];
	then
		sudo sed -i '/GRUB_TIMEOUT_STYLE=/d' /etc/default/grub;
		sudo sed -i '$a\GRUB_TIMEOUT_STYLE=""' /etc/default/grub;
		sudo update-grub;
fi
grub_timeout=`egrep -c 'GRUB_TIMEOUT="10"' /etc/default/grub`;
if [ "$grub_timeout" = "0" ];
	then
		sudo sed -i '/GRUB_TIMEOUT=/d' /etc/default/grub;
		sudo sed -i '$a\GRUB_TIMEOUT="10"' /etc/default/grub;
		sudo update-grub;
fi

#Desabilitar o chash report
crash_report=`egrep -c 'enabled=1' /etc/default/apport`;
if [ "$crash_report" = "1" ];
	then
		sudo sed -i 's/enabled=1/enabled=0/g' /etc/default/apport;
fi

#Arranxo do filtro rápido do synaptic
sudo killall synaptic;
pkg_aptxapianindex=$(dpkg-query -W --showformat='${Status}\n' apt-xapian-index|grep "install ok installed");
if [ 'install ok installed' != "$pkg_aptxapianindex" ];
	then
		sudo apt install -y apt-xapian-index;
		sudo update-apt-xapian-index -vf;
fi
