#!/bin/sh
#
#Borrado do script que permite que o lanzador do Ubiquity xerado polo PinguyBuilder poida ser empregado
if [ -f /usr/bin/instalador ];
	then
		sudo rm -f /usr/bin/instalador;
fi

#Borrado do script que comproba que ao iniciar sesión adminpc se empregue o script instalador anterior no Ubiquity
if [ -f /usr/bin/arranxaubiquity ];
	then
		sudo rm -f /usr/bin/arranxaubiquity;
fi
if [ -f /home/adminpc/.config/autostart/arranxaubiquity.desktop ];
	then
		sudo rm -f /home/adminpc/.config/autostart/arranxaubiquity.desktop;
fi

#Corrección do ficheiro sudoers para que deixe de autorizar sen contrasinal os scripts instalador e arranxaubiquity
if [ -f /etc/sudoers.backup ];
	then
		sudo mv -f /etc/sudoers.backup /etc/sudoers;
fi
 
#Desinstalación do PinguyBuilder
pkg_pinguybuilder=$(dpkg-query -W --showformat='${Status}\n' pinguybuilder-menu-based|grep "install ok installed");
if [ 'install ok installed' = "$pkg_pinguybuilder" ];
	then
		sudo apt remove -y pinguybuilder-menu-based;
fi
clear;
